name: CI

on: [ push, pull_request ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.2', '7.4', '8.0', '8.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: /
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql
          tools: cs2pr, phpcs, phpstan, psalm
      # run: phpstan analyze src --level=5 --error-format=checkstyle | cs2pr
      # 8- Run Psalm scan
      - name: Run Psalm scan
        run: psalm --threads=8 --shepherd --stats --output-format=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
